import {Foodspot,Greenharbor,Infest,Noter,Opensource, FoodspotThumb, GreenharborThumb,InfestThumb,OpensourceThumb,Coderscave,CoderscaveThumb,Prodata,ProdataThumb} from "../../assets/Images/Projects/index.js";


const AllProjectsData = [
    {
        thumbnail:GreenharborThumb,
        img1:Greenharbor,
        title:"GreenHarbor",
        category:"Web Development",
        top5:true,
        desc1:"GreenHarbor, born out of the 2024 Google Solution Challenge, is a beacon of hope for farmers worldwide. Its mission is clear: to transform traditional agricultural practices into modern, sustainable methods through the power of technology. By centralizing invaluable resources and connecting farmers with agricultural experts, GreenHarbor empowers individuals in the farming community to unlock their full potential.",
        desc2:"Through an intuitive interface, GreenHarbor offers farmers access to cutting-edge seeds, expert advice, and comprehensive training materials. By bridging the gap between tradition and innovation, this platform not only elevates agricultural productivity but also fosters a global community of knowledge-sharing and collaboration. ",
        github:"https://github.com/BALASANTHOSH01/Google_Solution_Challenge_2024",
        website:"https://greenharbor.netlify.app/",
        technology:["Reactjs ,","TailwindCSS ,","Netlify ,","Gemini API ,"],
    },
    {
        thumbnail:OpensourceThumb,
        img1:Opensource,
        title:"OpenHire",
        category:"Web Development",
        top5:true,
        desc1:"Introducing OpenHire, an innovative open-source Resource Management System (RMS) revolutionizing the recruitment landscape. OpenHire offers a comprehensive suite of features designed to streamline the hiring process, from candidate sourcing through diverse channels to managing job postings and evaluating applicants.",
        desc2:"OpenHire embraces modern recruitment practices by facilitating virtual interviews, enabling seamless connections between hiring managers and candidates regardless of geographical barriers. Additionally, with support for multiple site job postings, organizations can expand their reach and attract a wider pool of qualified candidates.",
        github:"https://github.com/BALASANTHOSH01/Next_Gen_RMS",
        website:"https://next-gen-rms.vercel.app/",
        technology:["ReactJS ,","TailwindCSS ,","Git ," ,"Github"],
    },
    {
        thumbnail:CoderscaveThumb,
        img1:Coderscave,
        title:"Coderscave",
        category:"Web Development",
        top5:true,
        desc1:"Coderscave is an innovative tech hub fostering a vibrant community of learners and creators. Through our virtual internship platform, we empower aspiring developers and enthusiasts to explore cutting-edge technologies. With hands-on experience and expert mentorship, Coderscave serves as a launchpad for talent in web development.",
        desc2:"At Coderscave, we're not just shaping the future; we're building it, one line of code at a time. Our passion for innovation extends beyond education to offering bespoke web development services for businesses. Leveraging expertise in tools like NextJS, TailwindCSS, and Chakra UI, we create solutions that elevate our clients' online presence.",
        github:"https://github.com/ManojKumar2920/nextjs-migrate",
        website:"https://www.coderscave.in",
        technology:["Reactjs ,","TailwindCSS ,","Vercel ,","chakra-ui "],
    },
    {
        thumbnail:Noter,
        img1:"",
        title:"Noter",
        category:"Web Development",
        top5:true,
        desc1:"Introducing Noter, the essential note-taking companion for the Naanmudhalvan project. Crafted using Django Python, Noter offers a seamless interface and robust functionalities to streamline note creation, organization, and retrieval.",
        desc2:"Noter&apos;s integration with Django Python ensures a secure and scalable platform, allowing for efficient data management and tailored customization to meet the unique needs of the Naanmudhalvan project. Simplify your note-taking process and enhance project productivity with Noter.",
        github:"https://github.com/BALASANTHOSH01/NaanMudhalvan_Django_Noter",
        website:"",
        technology:["python ,","Django"],
    },
    {
        thumbnail:InfestThumb,
        img1:Infest,
        title:"Infest2k24",
        category:"Web Development",
        top5:true,
        desc1:"INFEST2K24, crafted by myself and a trusted friend, epitomized our dedication to innovation in organizing our college&apos;s premier national-level symposium. Serving as the central hub for event activities, the website provided easy access to schedules, competitions, registrations, and speaker profiles.",
        desc2:"As the pioneering digital platform for our symposium, INFEST2K24 not only elevated visibility but also set a new standard for future editions. Its creation represented our commitment to excellence and our desire to provide an unforgettable experience for all involved. Through INFEST2K24, we celebrated innovation and laid the foundation for continued success in hosting impactful symposiums.",
        github:"https://github.com/ManojKumar2920/infest2k24",
        website:"https://infest2k24.vercel.app/",
        technology:["ReactJS ,","TailwindCSS ,","Vercel ,","ChakraUI ,","ParticlesJS"],
    },
    {
        thumbnail:FoodspotThumb,
        img1:Foodspot,
        title:"Foodspot",
        category:"Web Development",
        top5:true,
        desc1:"Welcome to our cutting-edge food ordering application, where convenience meets culinary excellence. With a user-friendly interface and an extensive selection of delectable dishes, our app revolutionizes the way you experience dining. From savory starters to decadent desserts, our curated menu caters to every craving and occasion, ensuring a delightful culinary adventure with every order.",
        desc2:"Designed to simplify your dining experience, our app offers seamless browsing, intuitive navigation, and personalized recommendations, making it effortless to discover new favorites and satisfy your appetite.",
        github:"https://github.com/BALASANTHOSH01/Food-Delivery-App",
        website:"https://foodspot-fwd.netlify.app/",
        technology:["ReactJS ,","TailwindCSS"],
    },
    {
        thumbnail:ProdataThumb,
        img1:Prodata,
        title:"Prodata",
        category:"Web Development",
        top5:false,
        desc1:"Prodata is a cutting-edge API project designed to streamline food product information retrieval. Utilizing the OpenFoodFacts API, users can effortlessly search for product details by simply entering the barcode into the intuitive input box. Developed using ReactJS and styled with TailwindCSS, Prodata offers a seamless and responsive user experience.",
        desc2:"As a self-made project, Prodata embodies innovation and efficiency. Hosted on Netlify, it exemplifies modern web development practices and utilizes REST API architecture to ensure fast and reliable data retrieval. With Prodata, accessing comprehensive food product information has never been easier, revolutionizing the way users interact with nutritional data.",
        github:"https://github.com/BALASANTHOSH01/Pro_Data",
        website:"https://prodataofficial.netlify.app/",
        technology:["Rest API ,","ReactJS ,","TailwindCSS ,","Netlify"],
    },
];

export default AllProjectsData;